export const products = [
  {
    id: "1",
    name: "Television",
    price: "500 euros",
    description: "Watching animated frames",
    img: "https://image.coolblue.be/max/500x500/products/1416067",
    availability: "in stock",
    release: "Released in 2023",
  },
  {
    id: "2",
    name: "Radio",
    price: "200 euros",
    description: "Listen to sweet tunes",
    img: "https://previews.123rf.com/images/artatrana/artatrana1601/artatrana160100001/51347962-modern-radio.jpg",
    availability: "in stock",
    release: "Released in 2023",
  },
  {
    id: "3",
    name: "Beamer",
    price: "400 euros",
    description: "Watching movies on the big screen",
    img: "https://media.s-bol.com/g7zK8yGDjjBk/RgEPN3L/550x511.jpg",
    availability: "in stock",
    release: "Released in 2023",
  },
  {
    id: "4",
    name: "Electric step",
    price: "300 euros",
    description: "Skeet skeet",
    img: "https://www.alternate.be/p/600x600/3/1/Xiaomi_Mi_Electric_Scooter_Pro_2_elektrische_step@@1651613.jpg",
    availability: "in stock",
    release: "Released in 2023",
  },
  {
    id: "5",
    name: "Toaster",
    price: "20 euros",
    description: "Make noice and crispy toast",
    img: "https://image.coolblue.be/max/500x500/products/1475080",
    availability: "in stock",
    release: "Released in 2023",
  },
];
